version: '3.7'
services:
  db:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
    networks:
      - smartbox
    restart: unless-stopped

  cache:
    image: redis:7.0.7-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - smartbox
    volumes: 
      - ./cache:/data
  
  main:
    build: 
      context: .
      dockerfile: ./docker/main/Dockerfile
    container_name: main
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - smartbox
    depends_on:
      - db

  consumer:
    build: 
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    container_name: consumer 
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - smartbox
    depends_on:
      - db

  migrate:
    profiles: ["tools"]
    image: migrate/migrate
    entrypoint: "migrate -path /tmp/migrations"
    command: ""
    env_file:
      - ./.env
    networks:
      - smartbox
    depends_on:
      - db
    volumes:
      - ./db/migration:/tmp/migrations

networks:
  smartbox:
    name: smartbox
    external: true